#!/bin/bash

[ -e services/evo_jdk8/em/embedded/rest/features-service/cp.txt ] || echo Missing: \"services/evo_jdk8/em/embedded/rest/features-service\"
[ -e services/evo_jdk8/em/embedded/rest/languagetool/cp.txt ] || echo Missing: \"services/evo_jdk8/em/embedded/rest/languagetool\"
[ -e services/evo_jdk8/em/embedded/rest/ncs/cp.txt ] || echo Missing: \"services/evo_jdk8/em/embedded/rest/ncs\"
[ -e services/evo_jdk8/em/embedded/rest/news/cp.txt ] || echo Missing: \"services/evo_jdk8/em/embedded/rest/news\"
[ -e services/evo_jdk8/em/embedded/rest/ocvn/cp.txt ] || echo Missing: \"services/evo_jdk8/em/embedded/rest/ocvn\"
[ -e services/evo_jdk8/em/embedded/rest/proxyprint/cp.txt ] || echo Missing: \"services/evo_jdk8/em/embedded/rest/proxyprint\"
[ -e services/evo_jdk8/em/embedded/rest/restcountries/cp.txt ] || echo Missing: \"services/evo_jdk8/em/embedded/rest/restcountries\"
[ -e services/evo_jdk8/em/embedded/rest/scout-api/cp.txt ] || echo Missing: \"services/evo_jdk8/em/embedded/rest/scout-api\"
[ -e services/evo_jdk8/em/embedded/rest/scs/cp.txt ] || echo Missing: \"services/evo_jdk8/em/embedded/rest/scs\"
[ -e services/jdk11/cwa-verification/em/embedded/rest/cwa-verification/cp.txt ] || echo Missing: \"services/jdk11/cwa-verification/em/embedded/rest/cwa-verification\"
[ -e services/jdk8/erc20-rest-service/build/libs/erc20-rest-service-0.1.0.jar ] || echo Missing: \"services/jdk8/erc20-rest-service/build/libs\"
[ -e services/jdk8/genome-nexus/web/target/web-0-unknown-version-SNAPSHOT.war ] || echo Missing: \"services/jdk8/genome-nexus/web/target\"
[ -e services/jdk8/person-controller/target/java-spring-boot-mongodb-starter-1.0.0.jar ] || echo Missing: \"services/jdk8/person-controller/target\"
[ -e services/jdk8/problem-controller/target/project-api-0.0.1.jar ] || echo Missing: \"services/jdk8/problem-controller/target\"
[ -e services/jdk8/rest-study/target/restful-web-services-0.0.1-SNAPSHOT.jar ] || echo Missing: \"services/jdk8/rest-study/target\"
[ -e services/jdk8/spring-batch-rest/example/api/target/spring-batch-rest-example-core-1.5.1.jar ] || echo Missing: \"services/jdk8/spring-batch-rest/example/api/target\"
[ -e services/jdk8/user-management/target/microdemo2-1.0.0-SNAPSHOT.jar ] || echo Missing: \"services/jdk8/user-management/target\"
[ -e services/jdk11/market/market-rest/target/market-rest-0.1.2.jar ] || echo Missing: \"services/jdk11/market/market-rest/target\"
[ -e services/jdk11/project-tracking-system/target/project-tracking-system.jar ] || echo Missing: \"services/jdk11/project-tracking-system/target\"